name: moat
version: 0.1
synopsis: Generate swift and kotlin types from haskell types
description: See README at <https://github.com/chessai/moat>
maintainer: chessai <chessai1996@gmail.com>
github: chessai/moat
category: Codegen, Text, TemplateHaskell
extra-source-files:
  - CHANGELOG.md
  - README.md

ghc-options: -Wall

default-extensions:
  - LambdaCase
  - RecordWildCards

dependencies:
  - base >= 4.11 && < 4.15
  - bytestring >= 0.10 && < 0.11
  - case-insensitive >= 1.2 && < 1.3
  - containers >= 0.5.9 && < 0.7
  - mtl >= 2.2 && < 2.3
  - primitive >= 0.6.4 && < 0.8
  - template-haskell >= 2.11 && < 2.17
  - text >= 1.2 && < 1.3
  - th-abstraction >= 0.3 && < 0.5
  - time >= 1.8 && < 1.11
  - unordered-containers >= 0.2 && < 0.3
  - uuid-types >= 1.0 && < 1.1
  - vector >= 0.12 && < 0.13

library:
  source-dirs: src
  exposed-modules:
    - Moat

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - hspec-golden
