name: moat
version: 0.1.1
synopsis: Generate swift and kotlin types from haskell types
description: See README at <https://github.com/chessai/moat>
maintainer: chessai <chessai1996@gmail.com>
github: chessai/moat
category: Codegen, Text, TemplateHaskell
extra-source-files:
  - CHANGELOG.md
  - README.md

ghc-options: -Wall

default-extensions:
  - LambdaCase
  - RecordWildCards

dependencies:
  - base >= 4.11 && < 4.18
  - bytestring >= 0.10 && < 0.12
  - case-insensitive >= 1.2 && < 1.3
  - containers >= 0.5.9 && < 0.7
  - mtl >= 2.2 && < 2.3
  - primitive >= 0.6.4 && < 0.8
  - template-haskell >= 2.11 && < 2.20
  - text >= 1.2 && < 2.1
  - th-abstraction >= 0.3 && < 0.5
  - th-compat >= 0.1.0 && < 0.2
  - time >= 1.8 && < 1.13
  - unordered-containers >= 0.2 && < 0.3
  - uuid-types >= 1.0 && < 1.1
  - vector >= 0.12 && < 0.13

build-tools:
  - hspec-discover

library:
  source-dirs: src
  exposed-modules:
    - Moat

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - hspec-golden
      - hspec-discover
    default-extensions:
      - AllowAmbiguousTypes
      - DataKinds
      - ScopedTypeVariables
      - TemplateHaskell
      - TypeApplications
    ghc-options:
      -Wno-unused-top-binds
