name: CI
on:
  check_suite:
    types: [completed]
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.10"]
        ghc: ["8.8.4", "8.10.7", "9.0.2", "9.2.8", "9.4.6", "9.6.3"]
    env:
      CONFIG: "--enable-tests"
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2.3
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal v2-update
      - run: cabal v2-freeze $CONFIG
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal v2-build --disable-optimization -j $CONFIG
      - run: cabal v2-test --disable-optimization -j $CONFIG
      - run: cabal v2-haddock -j $CONFIG
      - run: cabal v2-sdist
